### ISSUE TITLE
Fix reconciliation

### ISSUE THREAD

**Issue by knutster** [smartmachine/crdb-operator#3]
Implement reconciliation in the controller to reflect updates made to the CR towards the K8s resources.

**Comment by knutster** [comment]
This is what the CR looks like:

```yaml
apiVersion: db.smartmachine.io/v1alpha1
kind: CockroachDB
metadata:
  name: crdb-test
  namespace: crdb
spec:
  cluster:
    image: cockroachdb/cockroach:v2.1.6
    size: 3
    requestMemory: 300Mi
    limitMemory: 500Mi
    storagePerNode: 100Gi
    maxUnavailable: 1
  client:
    enable: true
  dashboard:
    enable: true
    nodePort: 31000
```
